"https://ageofempires.fandom.com/wiki/Dark_Age_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Feudal_Age_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Castle_Age_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Imperial_Age_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Militia_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Man-at-Arms_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Long_Swordsman_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Two-Handed_Swordsman 
"
"https://ageofempires.fandom.com/wiki/Champion 
"
"https://ageofempires.fandom.com/wiki/Spearman_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Pikeman_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Halberdier_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Eagle_Scout_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Eagle_Warrior 
"
"https://ageofempires.fandom.com/wiki/Elite_Eagle_Warrior 
"
"https://ageofempires.fandom.com/wiki/Supplies 
"
"https://ageofempires.fandom.com/wiki/Squires 
"
"https://ageofempires.fandom.com/wiki/Condottiero 
"
"https://ageofempires.fandom.com/wiki/Arson 
"
"https://ageofempires.fandom.com/wiki/Template:Buildings_AoE2 
"
"https://ageofempires.fandom.com/wiki/House_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Town_Center_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Blacksmith_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Archery_Range_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Tower 
"
"https://ageofempires.fandom.com/wiki/Outpost_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Wall 
"
"https://ageofempires.fandom.com/wiki/Palisade_Wall_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Scout_Cavalry_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Light_Cavalry_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Hussar_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Winged_Hussar_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Bloodlines 
"
"https://ageofempires.fandom.com/wiki/Knight_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Cavalier 
"
"https://ageofempires.fandom.com/wiki/Paladin 
"
"https://ageofempires.fandom.com/wiki/Camel_Scout 
"
"https://ageofempires.fandom.com/wiki/Camel_Rider_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Heavy_Camel_Rider 
"
"https://ageofempires.fandom.com/wiki/Imperial_Camel_Rider 
"
"https://ageofempires.fandom.com/wiki/Shrivamsha_Rider 
"
"https://ageofempires.fandom.com/wiki/Battle_Elephant 
"
"https://ageofempires.fandom.com/wiki/Elite_Battle_Elephant 
"
"https://ageofempires.fandom.com/wiki/Steppe_Lancer 
"
"https://ageofempires.fandom.com/wiki/Elite_Steppe_Lancer 
"
"https://ageofempires.fandom.com/wiki/Husbandry_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Barracks_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Archer_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Crossbowman_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Arbalester 
"
"https://ageofempires.fandom.com/wiki/Skirmisher_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Elite_Skirmisher 
"
"https://ageofempires.fandom.com/wiki/Imperial_Skirmisher 
"
"https://ageofempires.fandom.com/wiki/Cavalry_Archer_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Heavy_Cavalry_Archer 
"
"https://ageofempires.fandom.com/wiki/Elephant_Archer_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Elite_Elephant_Archer 
"
"https://ageofempires.fandom.com/wiki/Slinger_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Hand_Cannoneer 
"
"https://ageofempires.fandom.com/wiki/Genitour 
"
"https://ageofempires.fandom.com/wiki/Thumb_Ring 
"
"https://ageofempires.fandom.com/wiki/Parthian_Tactics 
"
"https://ageofempires.fandom.com/wiki/Battering_Ram_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Capped_Ram 
"
"https://ageofempires.fandom.com/wiki/Siege_Ram 
"
"https://ageofempires.fandom.com/wiki/Armored_Elephant_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Siege_Elephant_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Mangonel_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Onager_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Siege_Onager 
"
"https://ageofempires.fandom.com/wiki/Scorpion 
"
"https://ageofempires.fandom.com/wiki/Heavy_Scorpion 
"
"https://ageofempires.fandom.com/wiki/Siege_Tower_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Bombard_Cannon 
"
"https://ageofempires.fandom.com/wiki/Houfnice 
"
"https://ageofempires.fandom.com/wiki/Fishing_Ship_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Fire_Galley_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Fire_Ship_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Fast_Fire_Ship 
"
"https://ageofempires.fandom.com/wiki/Transport_Ship_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Trade_Cog 
"
"https://ageofempires.fandom.com/wiki/Gillnets 
"
"https://ageofempires.fandom.com/wiki/Cannon_Galleon 
"
"https://ageofempires.fandom.com/wiki/Elite_Cannon_Galleon 
"
"https://ageofempires.fandom.com/wiki/Demolition_Raft 
"
"https://ageofempires.fandom.com/wiki/Demolition_Ship_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Heavy_Demolition_Ship 
"
"https://ageofempires.fandom.com/wiki/Galley_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/War_Galley_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Galleon_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Longboat_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Turtle_Ship 
"
"https://ageofempires.fandom.com/wiki/Caravel_(Age_of_Empires_II) 
"
"https://ageofempires.fandom.com/wiki/Thirisadai 
"
"https://ageofempires.fandom.com/wiki/Careening 
"
"https://ageofempires.fandom.com/wiki/Dry_Dock 
"
"https://ageofempires.fandom.com/wiki/Shipwright 
"
