/wiki/Longbowman_(Age_of_Empires_II) 
/wiki/Cataphract_(Age_of_Empires_II) 
/wiki/Woad_Raider 
/wiki/Chu_Ko_Nu_(Age_of_Empires_II) 
/wiki/Throwing_Axeman_(Age_of_Empires_II) 
/wiki/Huskarl_(Age_of_Empires_II) 
/wiki/Samurai_(Age_of_Empires_II) 
/wiki/Mangudai_(Age_of_Empires_II) 
/wiki/War_Elephant_(Age_of_Empires_II) 
/wiki/Mameluke_(Age_of_Empires_II) 
/wiki/Armor_class:_Cavalry 
/wiki/Teutonic_Knight 
/wiki/Janissary_(Age_of_Empires_II) 
/wiki/Berserk 
/wiki/Jaguar_Warrior 
/wiki/Tarkan 
/wiki/War_Wagon_(Age_of_Empires_II) 
/wiki/Plumed_Archer 
/wiki/Conquistador_(Age_of_Empires_II) 
/wiki/Gunpowder_unit_(Age_of_Empires_II) 
/wiki/Monk_(Age_of_Empires_II) 
/wiki/Kamayuk 
/wiki/Elephant_Archer_(Age_of_Empires_II) 
/wiki/Heavy_Camel_Rider 
/wiki/Genoese_Crossbowman 
/wiki/Magyar_Huszar 
/wiki/Boyar_(Age_of_Empires_II) 
/wiki/Camel_Archer_(Age_of_Empires_II) 
/wiki/Shotel_Warrior_(Age_of_Empires_II) 
/wiki/Gbeto 
/wiki/Organ_Gun_(Age_of_Empires_II) 
/wiki/Siege_weapon_(Age_of_Empires_II) 
/wiki/Arambai 
/wiki/Gunpowder_unit_(Age_of_Empires_II) 
/wiki/Ballista_Elephant 
/wiki/Siege_weapon_(Age_of_Empires_II) 
/wiki/Karambit_Warrior 
/wiki/Rattan_Archer 
/wiki/Konnik 
/wiki/Kipchak 
/wiki/Leitis 
/wiki/Keshik_(Age_of_Empires_II) 
/wiki/Armor_class:_War_elephant 
/wiki/Coustillier 
/wiki/Villager_(Age_of_Empires_II) 
/wiki/Serjeant 
/wiki/Hussite_Wagon 
/wiki/Siege_weapon_(Age_of_Empires_II) 
/wiki/Siege_weapon_(Age_of_Empires_II) 
/wiki/Bombard_Cannon 
/wiki/Obuch 
/wiki/Urumi_Swordsman_(Age_of_Empires_II) 
/wiki/Chakram_Thrower 
/wiki/Pass-through_damage 
/wiki/Ghulam 
/wiki/Heavy_Camel_Rider 
