{ 'Militia': { 'name': 'Militia',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': 'Infantry',
               'civilization': 'Generic',
               'age_available': 'Dark Age',
               'trained_at': ['Barracks'],
               'cost': {'food': 60, 'wood': 0, 'gold': 20},
               'errors': {}},
  'Man-at-Arms': { 'name': 'Man-at-Arms',
                   'added_in': 'Age of Empires II: The Age of Kings',
                   'type': 'Infantry',
                   'civilization': 'Generic',
                   'age_available': 'Feudal Age',
                   'trained_at': ['Barracks'],
                   'cost': {'food': 60, 'wood': 0, 'gold': 20},
                   'errors': {}},
  'Long Swordsman': { 'name': 'Long Swordsman',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Infantry',
                      'civilization': 'Generic',
                      'age_available': 'Castle Age',
                      'trained_at': ['Barracks'],
                      'cost': {'food': 60, 'wood': 0, 'gold': 20},
                      'errors': {}},
  'Two-Handed Swordsman': { 'name': 'Two-Handed Swordsman',
                            'added_in': 'Age of Empires II: The Age of Kings',
                            'type': 'Infantry',
                            'civilization': 'Generic',
                            'age_available': 'Imperial Age',
                            'trained_at': ['Barracks'],
                            'cost': {'food': 60, 'wood': 0, 'gold': 20},
                            'errors': {}},
  'Champion': { 'name': 'Champion',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Infantry',
                'civilization': 'Generic',
                'age_available': 'Imperial Age',
                'trained_at': ['Barracks'],
                'cost': {'food': 60, 'wood': 0, 'gold': 20},
                'errors': {}},
  'Spearman': { 'name': 'Spearman',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Infantry',
                'civilization': 'Generic',
                'age_available': 'Feudal Age',
                'trained_at': ['Barracks'],
                'cost': {'food': 35, 'wood': 25, 'gold': 0},
                'errors': {}},
  'Pikeman': { 'name': 'Pikeman',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': 'Infantry',
               'civilization': 'Generic',
               'age_available': 'Castle Age',
               'trained_at': ['Barracks'],
               'cost': {'food': 35, 'wood': 25, 'gold': 0},
               'errors': {}},
  'Halberdier': { 'name': 'Halberdier',
                  'added_in': 'Age of Empires II: The Conquerors',
                  'type': 'Infantry',
                  'civilization': 'Generic',
                  'age_available': 'Imperial Age',
                  'trained_at': ['Barracks'],
                  'cost': {'food': 35, 'wood': 25, 'gold': 0},
                  'errors': {}},
  'Eagle Scout': { 'name': 'Eagle Scout',
                   'added_in': 'Age of Empires II HD: The Forgotten',
                   'type': 'Infantry',
                   'civilization': ['Aztecs', 'Incas', 'Mayans'],
                   'age_available': 'Feudal Age',
                   'trained_at': ['Barracks'],
                   'cost': {'food': 20, 'wood': 0, 'gold': 50},
                   'errors': {}},
  'Eagle Warrior': { 'name': 'Eagle Warrior',
                     'added_in': 'Age of Empires II: The Conquerors',
                     'type': 'Infantry',
                     'civilization': ['Aztecs', 'Incas', 'Mayans'],
                     'age_available': 'Castle Age',
                     'trained_at': ['Barracks'],
                     'cost': {'food': 20, 'wood': 0, 'gold': 50},
                     'errors': {}},
  'Elite Eagle Warrior': { 'name': 'Elite Eagle Warrior',
                           'added_in': 'Age of Empires II: The Conquerors',
                           'type': 'Infantry',
                           'civilization': ['Aztecs', 'Incas', 'Mayans'],
                           'age_available': 'Imperial Age',
                           'trained_at': ['Barracks'],
                           'cost': {'food': 20, 'wood': 0, 'gold': 50},
                           'errors': {}},
  'Aztecs': { 'name': 'Aztecs',
              'added_in': 'Age of Empires II: The Conquerors',
              'type': None,
              'civilization': None,
              'age_available': None,
              'trained_at': None,
              'cost': {'food': 0, 'wood': 0, 'gold': 0},
              'errors': { 'TypeError': "'NoneType' object has no attribute "
                                       "'find'",
                          'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                          'AgeError': "'NoneType' object has no attribute "
                                      "'find'",
                          'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Incas': { 'name': 'Incas',
             'added_in': 'Age of Empires II HD: The Forgotten',
             'type': None,
             'civilization': None,
             'age_available': None,
             'trained_at': None,
             'cost': {'food': 0, 'wood': 0, 'gold': 0},
             'errors': { 'TypeError': "'NoneType' object has no attribute "
                                      "'find'",
                         'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                         'AgeError': "'NoneType' object has no attribute "
                                     "'find'",
                         'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Mayans': { 'name': 'Mayans',
              'added_in': 'Age of Empires II: The Conquerors',
              'type': None,
              'civilization': None,
              'age_available': None,
              'trained_at': None,
              'cost': {'food': 0, 'wood': 0, 'gold': 0},
              'errors': { 'TypeError': "'NoneType' object has no attribute "
                                       "'find'",
                          'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                          'AgeError': "'NoneType' object has no attribute "
                                      "'find'",
                          'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Condottiero': { 'name': 'Condottiero',
                   'added_in': 'Age of Empires II HD: The Forgotten',
                   'type': 'Infantry',
                   'civilization': ['Italians'],
                   'age_available': 'Imperial Age',
                   'trained_at': ['Barracks'],
                   'cost': {'food': 50, 'wood': 0, 'gold': 35},
                   'errors': {}},
  'Italians': { 'name': 'Italians',
                'added_in': 'Age of Empires II HD: The Forgotten',
                'type': None,
                'civilization': None,
                'age_available': None,
                'trained_at': None,
                'cost': {'food': 0, 'wood': 0, 'gold': 0},
                'errors': { 'TypeError': "'NoneType' object has no attribute "
                                         "'find'",
                            'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                            'AgeError': "'NoneType' object has no attribute "
                                        "'find'",
                            'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Huskarl': { 'name': 'Huskarl',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': 'Infantry',
               'civilization': ['Goths'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle', 'Barracks'],
               'cost': {'food': 56, 'wood': 0, 'gold': 28},
               'errors': {}},
  'Goths': { 'name': 'Goths',
             'added_in': 'Age of Empires II: The Age of Kings',
             'type': None,
             'civilization': None,
             'age_available': None,
             'trained_at': None,
             'cost': {'food': 0, 'wood': 0, 'gold': 0},
             'errors': { 'TypeError': "'NoneType' object has no attribute "
                                      "'find'",
                         'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                         'AgeError': "'NoneType' object has no attribute "
                                     "'find'",
                         'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Anarchy': { 'name': 'Anarchy',
               'added_in': 'Age of Empires II: The Conquerors',
               'type': None,
               'civilization': None,
               'age_available': 'Castle Age',
               'trained_at': ['Castle'],
               'cost': {'food': 450, 'wood': 0, 'gold': 250},
               'errors': { 'TypeError': "'NoneType' object has no attribute "
                                        "'find'",
                           'CivError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Archer': { 'name': 'Archer',
              'added_in': 'Age of Empires II: The Age of Kings',
              'type': 'Foot archer',
              'civilization': 'Generic',
              'age_available': 'Feudal Age',
              'trained_at': ['Archery Range'],
              'cost': {'food': 0, 'wood': 25, 'gold': 45},
              'errors': {}},
  'Crossbowman': { 'name': 'Crossbowman',
                   'added_in': 'Age of Empires II: The Age of Kings',
                   'type': 'Foot archer',
                   'civilization': 'Generic',
                   'age_available': 'Castle Age',
                   'trained_at': ['Archery Range'],
                   'cost': {'food': 0, 'wood': 25, 'gold': 45},
                   'errors': {}},
  'Arbalester': { 'name': 'Arbalester',
                  'added_in': 'Age of Empires II: The Age of Kings',
                  'type': 'Foot archer',
                  'civilization': 'Generic',
                  'age_available': 'Imperial Age',
                  'trained_at': ['Archery Range'],
                  'cost': {'food': 0, 'wood': 25, 'gold': 45},
                  'errors': {}},
  'Skirmisher': { 'name': 'Skirmisher',
                  'added_in': '',
                  'type': 'Foot archer',
                  'civilization': 'Generic',
                  'age_available': 'Feudal Age',
                  'trained_at': ['Archery Range'],
                  'cost': {'food': 25, 'wood': 35, 'gold': 0},
                  'errors': {}},
  'Elite Skirmisher': { 'name': 'Elite Skirmisher',
                        'added_in': 'Age of Empires II: The Age of Kings',
                        'type': 'Foot archer',
                        'civilization': 'Generic',
                        'age_available': 'Castle Age',
                        'trained_at': ['Archery Range'],
                        'cost': {'food': 25, 'wood': 35, 'gold': 0},
                        'errors': {}},
  'Imperial Skirmisher': { 'name': 'Imperial Skirmisher',
                           'added_in': '',
                           'type': 'Foot archer',
                           'civilization': ['Vietnamese'],
                           'age_available': 'Imperial Age',
                           'trained_at': ['Archery Range'],
                           'cost': {'food': 25, 'wood': 35, 'gold': 0},
                           'errors': {}},
  'Vietnamese': { 'name': 'Vietnamese',
                  'added_in': 'Age of Empires II HD: Rise of the Rajas',
                  'type': None,
                  'civilization': None,
                  'age_available': None,
                  'trained_at': None,
                  'cost': {'food': 0, 'wood': 0, 'gold': 0},
                  'errors': { 'TypeError': "'NoneType' object has no attribute "
                                           "'find'",
                              'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                              'AgeError': "'NoneType' object has no attribute "
                                          "'find'",
                              'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Cavalry Archer': { 'name': 'Cavalry Archer',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Mounted Archer',
                      'civilization': 'Generic',
                      'age_available': 'Castle Age',
                      'trained_at': ['Archery Range'],
                      'cost': {'food': 0, 'wood': 40, 'gold': 60},
                      'errors': {}},
  'Heavy Cavalry Archer': { 'name': 'Heavy Cavalry Archer',
                            'added_in': 'Age of Empires II: The Age of Kings',
                            'type': 'Mounted archer',
                            'civilization': 'Generic',
                            'age_available': 'Imperial Age',
                            'trained_at': ['Archery Range'],
                            'cost': {'food': 0, 'wood': 40, 'gold': 60},
                            'errors': {}},
  'Hand Cannoneer': { 'name': 'Hand Cannoneer',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Gunpowder unit',
                      'civilization': 'Generic',
                      'age_available': 'Imperial Age',
                      'trained_at': ['Archery Range'],
                      'cost': {'food': 45, 'wood': 0, 'gold': 50},
                      'errors': {}},
  'Elephant Archer': { 'name': 'Elephant Archer',
                       'added_in': 'Age of Empires II HD: The Forgotten',
                       'type': 'Mounted archer',
                       'civilization': ['Bengalis', 'Dravidians', 'Gurjaras'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Archery Range'],
                       'cost': {'food': 80, 'wood': 0, 'gold': 70},
                       'errors': {}},
  'Elite Elephant Archer': { 'name': 'Elite Elephant Archer',
                             'added_in': 'Age of Empires II HD: The Forgotten',
                             'type': 'Mounted archer',
                             'civilization': [ 'Bengalis',
                                               'Dravidians',
                                               'Gurjaras'],
                             'age_available': 'Imperial Age',
                             'trained_at': ['Archery Range'],
                             'cost': {'food': 80, 'wood': 0, 'gold': 70},
                             'errors': {}},
  'Bengalis': { 'name': 'Bengalis',
                'added_in': 'Age of Empires II: Definitive Edition - Dynasties '
                            'of India',
                'type': None,
                'civilization': None,
                'age_available': None,
                'trained_at': None,
                'cost': {'food': 0, 'wood': 0, 'gold': 0},
                'errors': { 'TypeError': "'NoneType' object has no attribute "
                                         "'find'",
                            'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                            'AgeError': "'NoneType' object has no attribute "
                                        "'find'",
                            'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Dravidians': { 'name': 'Dravidians',
                  'added_in': 'Age of Empires II: Definitive Edition - '
                              'Dynasties of India',
                  'type': None,
                  'civilization': None,
                  'age_available': None,
                  'trained_at': None,
                  'cost': {'food': 0, 'wood': 0, 'gold': 0},
                  'errors': { 'TypeError': "'NoneType' object has no attribute "
                                           "'find'",
                              'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                              'AgeError': "'NoneType' object has no attribute "
                                          "'find'",
                              'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Gurjaras': { 'name': 'Gurjaras',
                'added_in': 'Age of Empires II: Definitive Edition - Dynasties '
                            'of India',
                'type': None,
                'civilization': None,
                'age_available': None,
                'trained_at': None,
                'cost': {'food': 0, 'wood': 0, 'gold': 0},
                'errors': { 'TypeError': "'NoneType' object has no attribute "
                                         "'find'",
                            'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                            'AgeError': "'NoneType' object has no attribute "
                                        "'find'",
                            'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Genitour': { 'name': 'Genitour',
                'added_in': 'Age of Empires II HD: The African Kingdoms',
                'type': 'Mounted Archer',
                'civilization': ['Berbers'],
                'age_available': 'Castle Age',
                'trained_at': ['Archery Range'],
                'cost': {'food': 40, 'wood': 35, 'gold': 0},
                'errors': {}},
  'Berbers': { 'name': 'Berbers',
               'added_in': 'Age of Empires II HD: The African Kingdoms',
               'type': None,
               'civilization': None,
               'age_available': None,
               'trained_at': None,
               'cost': {'food': 0, 'wood': 0, 'gold': 0},
               'errors': { 'TypeError': "'NoneType' object has no attribute "
                                        "'find'",
                           'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                           'AgeError': "'NoneType' object has no attribute "
                                       "'find'",
                           'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Slinger': { 'name': 'Slinger',
               'added_in': 'Age of Empires II HD: The Forgotten',
               'type': 'Foot archer',
               'civilization': ['Incas'],
               'age_available': 'Castle Age',
               'trained_at': ['Archery Range'],
               'cost': {'food': 30, 'wood': 0, 'gold': 40},
               'errors': {}},
  'Scout Cavalry': { 'name': 'Scout Cavalry',
                     'added_in': 'Age of Empires II: The Age of Kings',
                     'type': 'Cavalry',
                     'civilization': 'Generic',
                     'age_available': 'Feudal Age',
                     'trained_at': ['Stable'],
                     'cost': {'food': 80, 'wood': 0, 'gold': 0},
                     'errors': {}},
  'Light Cavalry': { 'name': 'Light Cavalry',
                     'added_in': 'Age of Empires II: The Age of Kings',
                     'type': 'Cavalry',
                     'civilization': 'Generic',
                     'age_available': 'Castle Age',
                     'trained_at': ['Stable'],
                     'cost': {'food': 80, 'wood': 0, 'gold': 0},
                     'errors': {}},
  'Hussar': { 'name': 'Hussar',
              'added_in': 'Age of Empires II: The Conquerors',
              'type': 'Cavalry',
              'civilization': 'Generic',
              'age_available': 'Imperial Age',
              'trained_at': ['Stable'],
              'cost': {'food': 80, 'wood': 0, 'gold': 0},
              'errors': {}},
  'Winged Hussar': { 'name': 'Winged Hussar',
                     'added_in': 'Age of Empires II: Definitive Edition - Dawn '
                                 'of the Dukes',
                     'type': 'Cavalry',
                     'civilization': ['Lithuanians', 'Poles'],
                     'age_available': 'Imperial Age',
                     'trained_at': ['Stable'],
                     'cost': {'food': 80, 'wood': 0, 'gold': 0},
                     'errors': {}},
  'Lithuanians': { 'name': 'Lithuanians',
                   'added_in': 'Age of Empires II: Definitive Edition - The '
                               'Last Khans',
                   'type': None,
                   'civilization': None,
                   'age_available': None,
                   'trained_at': None,
                   'cost': {'food': 0, 'wood': 0, 'gold': 0},
                   'errors': { 'TypeError': "'NoneType' object has no "
                                            "attribute 'find'",
                               'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                               'AgeError': "'NoneType' object has no attribute "
                                           "'find'",
                               'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Poles': { 'name': 'Poles',
             'added_in': 'Age of Empires II: Definitive Edition - Dawn of the '
                         'Dukes',
             'type': None,
             'civilization': None,
             'age_available': None,
             'trained_at': ['Folwark'],
             'cost': {'food': 0, 'wood': 0, 'gold': 0},
             'errors': { 'TypeError': "'NoneType' object has no attribute "
                                      "'find'",
                         'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                         'AgeError': "'NoneType' object has no attribute "
                                     "'find'"}},
  'Knight': { 'name': 'Knight',
              'added_in': 'Age of Empires II: The Age of Kings',
              'type': 'Cavalry',
              'civilization': 'Generic',
              'age_available': 'Castle Age',
              'trained_at': ['Stable'],
              'cost': {'food': 60, 'wood': 0, 'gold': 75},
              'errors': {}},
  'Cavalier': { 'name': 'Cavalier',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Cavalry',
                'civilization': 'Generic',
                'age_available': 'Imperial Age',
                'trained_at': ['Stable'],
                'cost': {'food': 60, 'wood': 0, 'gold': 75},
                'errors': {}},
  'Paladin': { 'name': 'Paladin',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': 'Cavalry',
               'civilization': 'Generic',
               'age_available': 'Imperial Age',
               'trained_at': ['Stable'],
               'cost': {'food': 60, 'wood': 0, 'gold': 75},
               'errors': {}},
  'Camel Scout': { 'name': 'Camel Scout',
                   'added_in': 'Age of Empires II: Definitive Edition - '
                               'Dynasties of India',
                   'type': 'Cavalry',
                   'civilization': ['Gurjaras'],
                   'age_available': 'Feudal Age',
                   'trained_at': ['Stable'],
                   'cost': {'food': 55, 'wood': 0, 'gold': 60},
                   'errors': {}},
  'Camel Rider': { 'name': 'Camel Rider',
                   'added_in': 'Age of Empires II: The Age of Kings',
                   'type': 'Cavalry',
                   'civilization': 'Generic',
                   'age_available': 'Castle Age',
                   'trained_at': ['Stable'],
                   'cost': {'food': 55, 'wood': 0, 'gold': 60},
                   'errors': {}},
  'Heavy Camel Rider': { 'name': 'Heavy Camel Rider',
                         'added_in': 'Age of Empires II: The Age of Kings',
                         'type': 'Cavalry',
                         'civilization': 'Generic',
                         'age_available': 'Imperial Age',
                         'trained_at': ['Stable'],
                         'cost': {'food': 55, 'wood': 0, 'gold': 60},
                         'errors': {}},
  'Imperial Camel Rider': { 'name': 'Imperial Camel Rider',
                            'added_in': 'Age of Empires II HD: The Forgotten',
                            'type': 'Cavalry',
                            'civilization': ['Hindustanis'],
                            'age_available': 'Imperial Age',
                            'trained_at': ['Stable'],
                            'cost': {'food': 55, 'wood': 0, 'gold': 60},
                            'errors': {}},
  'Hindustanis': { 'name': 'Hindustanis',
                   'added_in': 'Age of Empires II: Definitive Edition - '
                               'Dynasties of India',
                   'type': None,
                   'civilization': None,
                   'age_available': None,
                   'trained_at': ['Caravanserai'],
                   'cost': {'food': 0, 'wood': 0, 'gold': 0},
                   'errors': { 'TypeError': "'NoneType' object has no "
                                            "attribute 'find'",
                               'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                               'AgeError': "'NoneType' object has no attribute "
                                           "'find'"}},
  'Battle Elephant': { 'name': 'Battle Elephant',
                       'added_in': 'Age of Empires II HD: Rise of the Rajas',
                       'type': 'Cavalry',
                       'civilization': [ 'Bengalis',
                                         'Burmese',
                                         'Dravidians',
                                         'Khmer',
                                         'Malay',
                                         'Vietnamese'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Stable'],
                       'cost': {'food': 110, 'wood': 0, 'gold': 70},
                       'errors': {}},
  'Elite Battle Elephant': { 'name': 'Elite Battle Elephant',
                             'added_in': 'Age of Empires II HD: Rise of the '
                                         'Rajas',
                             'type': 'Cavalry',
                             'civilization': [ 'Bengalis',
                                               'Burmese',
                                               'Khmer',
                                               'Malay',
                                               'Vietnamese'],
                             'age_available': 'Imperial Age',
                             'trained_at': ['Stable'],
                             'cost': {'food': 110, 'wood': 0, 'gold': 70},
                             'errors': {}},
  'Steppe Lancer': { 'name': 'Steppe Lancer',
                     'added_in': 'Age of Empires II: Definitive Edition - The '
                                 'Last Khans',
                     'type': 'Cavalry',
                     'civilization': ['Cumans', 'Mongols', 'Tatars'],
                     'age_available': 'Castle Age',
                     'trained_at': ['Stable'],
                     'cost': {'food': 70, 'wood': 0, 'gold': 40},
                     'errors': {}},
  'Elite Steppe Lancer': { 'name': 'Elite Steppe Lancer',
                           'added_in': 'Age of Empires II: Definitive Edition '
                                       '- The Last Khans',
                           'type': 'Cavalry',
                           'civilization': ['Cumans', 'Mongols', 'Tatars'],
                           'age_available': 'Imperial Age',
                           'trained_at': ['Stable'],
                           'cost': {'food': 70, 'wood': 0, 'gold': 40},
                           'errors': {}},
  'Cumans': { 'name': 'Cumans',
              'added_in': 'Age of Empires II: Definitive Edition - The Last '
                          'Khans',
              'type': None,
              'civilization': None,
              'age_available': None,
              'trained_at': None,
              'cost': {'food': 0, 'wood': 0, 'gold': 0},
              'errors': { 'TypeError': "'NoneType' object has no attribute "
                                       "'find'",
                          'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                          'AgeError': "'NoneType' object has no attribute "
                                      "'find'",
                          'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Mongols': { 'name': 'Mongols',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': None,
               'civilization': None,
               'age_available': None,
               'trained_at': None,
               'cost': {'food': 0, 'wood': 0, 'gold': 0},
               'errors': { 'TypeError': "'NoneType' object has no attribute "
                                        "'find'",
                           'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                           'AgeError': "'NoneType' object has no attribute "
                                       "'find'",
                           'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Tatars': { 'name': 'Tatars',
              'added_in': 'Age of Empires II: Definitive Edition - The Last '
                          'Khans',
              'type': None,
              'civilization': None,
              'age_available': None,
              'trained_at': None,
              'cost': {'food': 0, 'wood': 0, 'gold': 0},
              'errors': { 'TypeError': "'NoneType' object has no attribute "
                                       "'find'",
                          'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                          'AgeError': "'NoneType' object has no attribute "
                                      "'find'",
                          'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Xolotl Warrior': { 'name': 'Xolotl Warrior',
                      'added_in': 'Age of Empires II: Definitive Edition - The '
                                  'Last Khans',
                      'type': 'Cavalry',
                      'civilization': ['Aztecs', 'Mayans', 'Incas'],
                      'age_available': 'Castle Age',
                      'trained_at': ['Stable'],
                      'cost': {'food': 60, 'wood': 0, 'gold': 75},
                      'errors': {}},
  'Shrivamsha Rider': { 'name': 'Shrivamsha Rider',
                        'added_in': 'Age of Empires II: Definitive Edition - '
                                    'Dynasties of India',
                        'type': 'Cavalry',
                        'civilization': ['Gurjaras'],
                        'age_available': 'Castle Age',
                        'trained_at': ['Stable'],
                        'cost': {'food': 70, 'wood': 0, 'gold': 20},
                        'errors': {}},
  'Tarkan': { 'name': 'Tarkan',
              'added_in': 'Age of Empires II: The Conquerors',
              'type': 'Cavalry',
              'civilization': ['Huns'],
              'age_available': 'Castle Age',
              'trained_at': ['Castle', ''],
              'cost': {'food': 60, 'wood': 0, 'gold': 60},
              'errors': {}},
  'Huns': { 'name': 'Huns',
            'added_in': 'Age of Empires II: The Conquerors',
            'type': None,
            'civilization': None,
            'age_available': None,
            'trained_at': None,
            'cost': {'food': 0, 'wood': 0, 'gold': 0},
            'errors': { 'TypeError': "'NoneType' object has no attribute "
                                     "'find'",
                        'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                        'AgeError': "'NoneType' object has no attribute 'find'",
                        'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Marauders': { 'name': 'Marauders',
                 'added_in': 'Age of Empires II HD: The Forgotten',
                 'type': None,
                 'civilization': None,
                 'age_available': 'Castle Age',
                 'trained_at': ['Castle'],
                 'cost': {'food': 0, 'wood': 300, 'gold': 200},
                 'errors': { 'TypeError': "'NoneType' object has no attribute "
                                          "'find'",
                             'CivError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Fishing Ship': { 'name': 'Fishing Ship',
                    'added_in': 'Age of Empires II: The Age of Kings',
                    'type': 'Civilian Ship',
                    'civilization': 'Generic',
                    'age_available': 'Dark Age',
                    'trained_at': ['Dock'],
                    'cost': {'food': 0, 'wood': 75, 'gold': 0},
                    'errors': {}},
  'Transport Ship': { 'name': 'Transport Ship',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Ship',
                      'civilization': 'Generic',
                      'age_available': 'Dark Age',
                      'trained_at': ['Dock', 'Harbor'],
                      'cost': {'food': 0, 'wood': 125, 'gold': 0},
                      'errors': {}},
  'Trade Cog': { 'name': 'Trade Cog',
                 'added_in': 'Age of Empires II: The Age of Kings',
                 'type': 'Civilian',
                 'civilization': 'Generic',
                 'age_available': 'Feudal Age',
                 'trained_at': ['Dock'],
                 'cost': {'food': 0, 'wood': 100, 'gold': 50},
                 'errors': {}},
  'Galley': { 'name': 'Galley',
              'added_in': 'Age of Empires II: The Age of Kings',
              'type': 'Ship',
              'civilization': 'Generic',
              'age_available': 'Feudal Age',
              'trained_at': ['Dock'],
              'cost': {'food': 0, 'wood': 90, 'gold': 30},
              'errors': {}},
  'War Galley': { 'name': 'War Galley',
                  'added_in': 'Age of Empires II: The Age of Kings',
                  'type': 'Ship',
                  'civilization': 'Generic',
                  'age_available': 'Castle Age',
                  'trained_at': None,
                  'cost': {'food': 0, 'wood': 90, 'gold': 30},
                  'errors': { 'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Galleon': { 'name': 'Galleon',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': 'Ship',
               'civilization': 'Generic',
               'age_available': 'Imperial Age',
               'trained_at': ['Dock'],
               'cost': {'food': 0, 'wood': 90, 'gold': 30},
               'errors': {}},
  'Fire Galley': { 'name': 'Fire Galley',
                   'added_in': 'Age of Empires II HD: The African Kingdoms',
                   'type': 'Ship',
                   'civilization': 'Generic',
                   'age_available': 'Feudal Age',
                   'trained_at': ['Dock'],
                   'cost': {'food': 0, 'wood': 75, 'gold': 45},
                   'errors': {}},
  'Fire Ship': { 'name': 'Fire Ship',
                 'added_in': 'Age of Empires II: The Age of Kings',
                 'type': 'Ship',
                 'civilization': 'Generic',
                 'age_available': 'Castle Age',
                 'trained_at': ['Dock'],
                 'cost': {'food': 0, 'wood': 75, 'gold': 45},
                 'errors': {}},
  'Fast Fire Ship': { 'name': 'Fast Fire Ship',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Ship',
                      'civilization': 'Generic',
                      'age_available': 'Imperial Age',
                      'trained_at': ['Dock'],
                      'cost': {'food': 0, 'wood': 75, 'gold': 45},
                      'errors': {}},
  'Demolition Raft': { 'name': 'Demolition Raft',
                       'added_in': 'Age of Empires II HD: The African Kingdoms',
                       'type': 'Ship',
                       'civilization': 'Generic',
                       'age_available': 'Feudal Age',
                       'trained_at': ['Dock'],
                       'cost': {'food': 0, 'wood': 70, 'gold': 50},
                       'errors': {}},
  'Demolition Ship': { 'name': 'Demolition Ship',
                       'added_in': 'Age of Empires II: The Age of Kings',
                       'type': 'Ship',
                       'civilization': 'Generic',
                       'age_available': 'Castle Age',
                       'trained_at': ['Dock'],
                       'cost': {'food': 0, 'wood': 70, 'gold': 50},
                       'errors': {}},
  'Heavy Demolition Ship': { 'name': 'Heavy Demolition Ship',
                             'added_in': 'Age of Empires II: The Age of Kings',
                             'type': 'Ship',
                             'civilization': 'Generic',
                             'age_available': 'Imperial Age',
                             'trained_at': ['Dock'],
                             'cost': {'food': 0, 'wood': 70, 'gold': 50},
                             'errors': {}},
  'Cannon Galleon': { 'name': 'Cannon Galleon',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Ship',
                      'civilization': 'Generic',
                      'age_available': 'Imperial Age',
                      'trained_at': ['Dock'],
                      'cost': {'food': 0, 'wood': 200, 'gold': 150},
                      'errors': {}},
  'Elite Cannon Galleon': { 'name': 'Elite Cannon Galleon',
                            'added_in': 'Age of Empires II: The Age of Kings',
                            'type': 'Ship',
                            'civilization': 'Generic',
                            'age_available': 'Imperial Age',
                            'trained_at': ['Dock'],
                            'cost': {'food': 0, 'wood': 200, 'gold': 150},
                            'errors': {}},
  'Longboat': { 'name': 'Longboat',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Ship',
                'civilization': ['Vikings'],
                'age_available': 'Castle Age',
                'trained_at': ['Dock'],
                'cost': {'food': 0, 'wood': 100, 'gold': 43},
                'errors': {}},
  'Vikings': { 'name': 'Vikings',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': None,
               'civilization': None,
               'age_available': None,
               'trained_at': None,
               'cost': {'food': 0, 'wood': 0, 'gold': 0},
               'errors': { 'TypeError': "'NoneType' object has no attribute "
                                        "'find'",
                           'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                           'AgeError': "'NoneType' object has no attribute "
                                       "'find'",
                           'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Turtle Ship': { 'name': 'Turtle Ship',
                   'added_in': 'Age of Empires II: The Conquerors',
                   'type': 'Ship',
                   'civilization': ['Koreans'],
                   'age_available': 'Castle Age',
                   'trained_at': ['Dock'],
                   'cost': {'food': 0, 'wood': 152, 'gold': 180},
                   'errors': {}},
  'Koreans': { 'name': 'Koreans',
               'added_in': 'Age of Empires II: The Conquerors',
               'type': None,
               'civilization': None,
               'age_available': None,
               'trained_at': None,
               'cost': {'food': 0, 'wood': 0, 'gold': 0},
               'errors': { 'TypeError': "'NoneType' object has no attribute "
                                        "'find'",
                           'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                           'AgeError': "'NoneType' object has no attribute "
                                       "'find'",
                           'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Caravel': { 'name': 'Caravel',
               'added_in': 'Age of Empires II HD: The African Kingdoms',
               'type': 'Ship',
               'civilization': ['Portuguese'],
               'age_available': 'Castle Age',
               'trained_at': ['Dock'],
               'cost': {'food': 0, 'wood': 90, 'gold': 34},
               'errors': {}},
  'Portuguese': { 'name': 'Portuguese',
                  'added_in': 'Age of Empires II HD: The African Kingdoms',
                  'type': None,
                  'civilization': None,
                  'age_available': None,
                  'trained_at': ['Feitoria'],
                  'cost': {'food': 0, 'wood': 0, 'gold': 0},
                  'errors': { 'TypeError': "'NoneType' object has no attribute "
                                           "'find'",
                              'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                              'AgeError': "'NoneType' object has no attribute "
                                          "'find'"}},
  'Thirisadai': { 'name': 'Thirisadai',
                  'added_in': 'Age of Empires II: Definitive Edition - '
                              'Dynasties of India',
                  'type': 'Ship',
                  'civilization': ['Dravidians'],
                  'age_available': 'Imperial Age',
                  'trained_at': ['Dock'],
                  'cost': {'food': 0, 'wood': 180, 'gold': 60},
                  'errors': {}},
  'Battering Ram': { 'name': 'Battering Ram',
                     'added_in': 'Age of Empires II: The Age of Kings',
                     'type': 'Siege unit',
                     'civilization': 'Generic',
                     'age_available': 'Castle Age',
                     'trained_at': ['Siege Workshop'],
                     'cost': {'food': 0, 'wood': 160, 'gold': 75},
                     'errors': {}},
  'Capped Ram': { 'name': 'Capped Ram',
                  'added_in': 'Age of Empires II: The Age of Kings',
                  'type': 'Siege unit',
                  'civilization': 'Generic',
                  'age_available': 'Imperial Age',
                  'trained_at': ['Siege Workshop'],
                  'cost': {'food': 0, 'wood': 160, 'gold': 75},
                  'errors': {}},
  'Siege Ram': { 'name': 'Siege Ram',
                 'added_in': 'Age of Empires II: The Age of Kings',
                 'type': 'Siege unit',
                 'civilization': 'Generic',
                 'age_available': 'Imperial Age',
                 'trained_at': ['Siege Workshop'],
                 'cost': {'food': 0, 'wood': 160, 'gold': 75},
                 'errors': {}},
  'Mangonel': { 'name': 'Mangonel',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Siege unit',
                'civilization': 'Generic',
                'age_available': 'Castle Age',
                'trained_at': ['Siege Workshop'],
                'cost': {'food': 0, 'wood': 160, 'gold': 135},
                'errors': {}},
  'Onager': { 'name': 'Onager',
              'added_in': 'Age of Empires II: The Age of Kings',
              'type': 'Siege unit',
              'civilization': 'Generic',
              'age_available': 'Imperial Age',
              'trained_at': ['Siege Workshop'],
              'cost': {'food': 0, 'wood': 160, 'gold': 135},
              'errors': {}},
  'Siege Onager': { 'name': 'Siege Onager',
                    'added_in': 'Age of Empires II: The Age of Kings',
                    'type': 'Siege unit',
                    'civilization': 'Generic',
                    'age_available': 'Imperial Age',
                    'trained_at': ['Siege Workshop'],
                    'cost': {'food': 0, 'wood': 160, 'gold': 135},
                    'errors': {}},
  'Scorpion': { 'name': 'Scorpion',
                'added_in': '',
                'type': 'Siege unit',
                'civilization': 'Generic',
                'age_available': 'Castle Age',
                'trained_at': ['Siege Workshop'],
                'cost': {'food': 0, 'wood': 75, 'gold': 75},
                'errors': {}},
  'Heavy Scorpion': { 'name': 'Heavy Scorpion',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Siege unit',
                      'civilization': 'Generic',
                      'age_available': 'Imperial Age',
                      'trained_at': ['Siege Workshop'],
                      'cost': {'food': 0, 'wood': 75, 'gold': 75},
                      'errors': {}},
  'Bombard Cannon': { 'name': 'Bombard Cannon',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Siege unit',
                      'civilization': 'Generic',
                      'age_available': 'Imperial Age',
                      'trained_at': ['Siege Workshop'],
                      'cost': {'food': 0, 'wood': 225, 'gold': 225},
                      'errors': {}},
  'Houfnice': { 'name': 'Houfnice',
                'added_in': 'Age of Empires II: Definitive Edition - Dawn of '
                            'the Dukes',
                'type': 'Siege unit',
                'civilization': ['Bohemians'],
                'age_available': 'Imperial Age',
                'trained_at': ['Siege Workshop'],
                'cost': {'food': 0, 'wood': 225, 'gold': 225},
                'errors': {}},
  'Bohemians': { 'name': 'Bohemians',
                 'added_in': 'Age of Empires II: Definitive Edition - Dawn of '
                             'the Dukes',
                 'type': None,
                 'civilization': None,
                 'age_available': None,
                 'trained_at': None,
                 'cost': {'food': 0, 'wood': 0, 'gold': 0},
                 'errors': { 'TypeError': "'NoneType' object has no attribute "
                                          "'find'",
                             'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                             'AgeError': "'NoneType' object has no attribute "
                                         "'find'",
                             'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Siege Tower': { 'name': 'Siege Tower',
                   'added_in': 'Age of Empires II HD: The African Kingdoms',
                   'type': 'Siege unit',
                   'civilization': 'Generic',
                   'age_available': 'Castle Age',
                   'trained_at': ['Siege Workshop'],
                   'cost': {'food': 0, 'wood': 200, 'gold': 160},
                   'errors': {}},
  'Armored Elephant': { 'name': 'Armored Elephant',
                        'added_in': 'Age of Empires II: Definitive Edition - '
                                    'Dynasties of India',
                        'type': 'Cavalry',
                        'civilization': [ 'Bengalis',
                                          'Dravidians',
                                          'Gurjaras',
                                          'Hindustanis'],
                        'age_available': 'Castle Age',
                        'trained_at': ['Siege Workshop'],
                        'cost': {'food': 130, 'wood': 0, 'gold': 95},
                        'errors': {}},
  'Siege Elephant': { 'name': 'Siege Elephant',
                      'added_in': 'Age of Empires II: Definitive Edition - '
                                  'Dynasties of India',
                      'type': 'Cavalry',
                      'civilization': [ 'Bengalis',
                                        'Dravidians',
                                        'Gurjaras',
                                        'Hindustanis'],
                      'age_available': 'Imperial Age',
                      'trained_at': ['Siege Workshop'],
                      'cost': {'food': 130, 'wood': 0, 'gold': 95},
                      'errors': {}},
  'Villager': { 'name': 'Villager',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': None,
                'civilization': 'Generic',
                'age_available': 'Dark Age',
                'trained_at': ['Town Center'],
                'cost': {'food': 50, 'wood': 0, 'gold': 0},
                'errors': { 'TypeError': "'NoneType' object has no attribute "
                                         "'text'"}},
  'Flemish Militia(Town Center)': { 'name': 'Flemish Militia(Town Center)',
                                    'added_in': 'Age of Empires II: Definitive '
                                                'Edition - Lords of the West',
                                    'type': 'Infantry',
                                    'civilization': ['Burgundians'],
                                    'age_available': 'Imperial Age',
                                    'trained_at': ['Town Center'],
                                    'cost': {'food': 60, 'wood': 0, 'gold': 25},
                                    'errors': {}},
  'Burgundians': { 'name': 'Burgundians',
                   'added_in': 'Age of Empires II: Definitive Edition - Lords '
                               'of the West',
                   'type': None,
                   'civilization': None,
                   'age_available': None,
                   'trained_at': None,
                   'cost': {'food': 0, 'wood': 0, 'gold': 0},
                   'errors': { 'TypeError': "'NoneType' object has no "
                                            "attribute 'find'",
                               'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                               'AgeError': "'NoneType' object has no attribute "
                                           "'find'",
                               'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Flemish Revolution': { 'name': 'Flemish Revolution',
                          'added_in': 'Age of Empires II: Definitive Edition - '
                                      'Lords of the West',
                          'type': None,
                          'civilization': None,
                          'age_available': 'Imperial Age',
                          'trained_at': ['Castle'],
                          'cost': {'food': 1200, 'wood': 0, 'gold': 650},
                          'errors': { 'TypeError': "'NoneType' object has no "
                                                   "attribute 'find'",
                                      'CivError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Monk': { 'name': 'Monk',
            'added_in': 'Age of Empires II: The Age of Kings',
            'type': None,
            'civilization': 'Generic',
            'age_available': 'Castle Age',
            'trained_at': ['Monastery'],
            'cost': {'food': 0, 'wood': 0, 'gold': 100},
            'errors': { 'TypeError': "'NoneType' object has no attribute "
                                     "'text'"}},
  'Missionary': { 'name': 'Missionary',
                  'added_in': 'Age of Empires II: The Conquerors',
                  'type': 'Cavalry',
                  'civilization': ['Spanish'],
                  'age_available': 'Castle Age',
                  'trained_at': ['Monastery'],
                  'cost': {'food': 0, 'wood': 0, 'gold': 100},
                  'errors': {}},
  'Spanish': { 'name': 'Spanish',
               'added_in': 'Age of Empires II: The Conquerors',
               'type': None,
               'civilization': None,
               'age_available': None,
               'trained_at': None,
               'cost': {'food': 0, 'wood': 0, 'gold': 0},
               'errors': { 'TypeError': "'NoneType' object has no attribute "
                                        "'find'",
                           'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                           'AgeError': "'NoneType' object has no attribute "
                                       "'find'",
                           'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Trade Cart': { 'name': 'Trade Cart',
                  'added_in': 'Age of Empires II: The Age of Kings',
                  'type': None,
                  'civilization': 'Generic',
                  'age_available': 'Feudal Age',
                  'trained_at': ['Market'],
                  'cost': {'food': 0, 'wood': 100, 'gold': 50},
                  'errors': { 'TypeError': "'NoneType' object has no attribute "
                                           "'text'"}},
  None: { 'name': None,
          'added_in': None,
          'type': None,
          'civilization': None,
          'age_available': None,
          'trained_at': None,
          'cost': {'food': 0, 'wood': 0, 'gold': 0},
          'errors': { 'NameError': "'NoneType' object has no attribute 'text'",
                      'AddedInError': "'NoneType' object has no attribute "
                                      "'find'",
                      'TypeError': "'NoneType' object has no attribute 'find'",
                      'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                      'AgeError': "'NoneType' object has no attribute 'find'",
                      'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Petard': { 'name': 'Petard',
              'added_in': 'Age of Empires II: The Conquerors',
              'type': 'Siege unit',
              'civilization': 'Generic',
              'age_available': 'Castle Age',
              'trained_at': ['Castle'],
              'cost': {'food': 65, 'wood': 0, 'gold': 20},
              'errors': {}},
  'Trebuchet': { 'name': 'Trebuchet',
                 'added_in': 'Age of Empires II: The Age of Kings',
                 'type': 'Siege unit',
                 'civilization': 'Generic',
                 'age_available': 'Imperial Age',
                 'trained_at': ['Castle'],
                 'cost': {'food': 0, 'wood': 200, 'gold': 200},
                 'errors': {}},
  'Longbowman': { 'name': 'Longbowman',
                  'added_in': 'Age of Empires II: The Age of Kings',
                  'type': 'Foot Archer',
                  'civilization': ['Britons'],
                  'age_available': 'Castle Age',
                  'trained_at': ['Castle'],
                  'cost': {'food': 0, 'wood': 35, 'gold': 40},
                  'errors': {}},
  'Cataphract': { 'name': 'Cataphract',
                  'added_in': 'Age of Empires II: The Age of Kings',
                  'type': 'Cavalry',
                  'civilization': ['Byzantines'],
                  'age_available': 'Castle Age',
                  'trained_at': ['Castle'],
                  'cost': {'food': 70, 'wood': 0, 'gold': 75},
                  'errors': {}},
  'Woad Raider': { 'name': 'Woad Raider',
                   'added_in': 'Age of Empires II: The Age of Kings',
                   'type': 'Infantry',
                   'civilization': ['Celts'],
                   'age_available': 'Castle Age',
                   'trained_at': ['Castle'],
                   'cost': {'food': 65, 'wood': 0, 'gold': 25},
                   'errors': {}},
  'Chu Ko Nu': { 'name': 'Chu Ko Nu',
                 'added_in': 'Age of Empires II: The Age of Kings',
                 'type': 'Foot archer',
                 'civilization': ['Chinese'],
                 'age_available': 'Castle Age',
                 'trained_at': ['Castle'],
                 'cost': {'food': 0, 'wood': 40, 'gold': 35},
                 'errors': {}},
  'Throwing Axeman': { 'name': 'Throwing Axeman',
                       'added_in': 'Age of Empires II: The Age of Kings',
                       'type': 'Infantry',
                       'civilization': ['Franks'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Castle'],
                       'cost': {'food': 55, 'wood': 0, 'gold': 25},
                       'errors': {}},
  'Samurai': { 'name': 'Samurai',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': 'Infantry',
               'civilization': ['Japanese'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle'],
               'cost': {'food': 60, 'wood': 0, 'gold': 30},
               'errors': {}},
  'Mangudai': { 'name': 'Mangudai',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Mounted archer',
                'civilization': ['Mongols'],
                'age_available': 'Castle Age',
                'trained_at': ['Castle'],
                'cost': {'food': 0, 'wood': 55, 'gold': 65},
                'errors': {}},
  'War Elephant': { 'name': 'War Elephant',
                    'added_in': 'Age of Empires II: The Age of Kings',
                    'type': 'Cavalry',
                    'civilization': ['Persians'],
                    'age_available': 'Castle Age',
                    'trained_at': ['Castle'],
                    'cost': {'food': 170, 'wood': 0, 'gold': 85},
                    'errors': {}},
  'Mameluke': { 'name': 'Mameluke',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Cavalry',
                'civilization': ['Saracens'],
                'age_available': 'Castle Age',
                'trained_at': ['Castle'],
                'cost': {'food': 55, 'wood': 0, 'gold': 85},
                'errors': {}},
  'Teutonic Knight': { 'name': 'Teutonic Knight',
                       'added_in': 'Age of Empires II: The Age of Kings',
                       'type': 'Infantry',
                       'civilization': ['Teutons'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Castle'],
                       'cost': {'food': 85, 'wood': 0, 'gold': 40},
                       'errors': {}},
  'Janissary': { 'name': 'Janissary',
                 'added_in': 'Age of Empires II: The Age of Kings',
                 'type': 'Gunpowder unit',
                 'civilization': ['Turks'],
                 'age_available': 'Castle Age',
                 'trained_at': ['Castle'],
                 'cost': {'food': 60, 'wood': 0, 'gold': 55},
                 'errors': {}},
  'Berserk': { 'name': 'Berserk',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': 'Infantry',
               'civilization': ['Vikings'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle'],
               'cost': {'food': 65, 'wood': 0, 'gold': 25},
               'errors': {}},
  'Jaguar Warrior': { 'name': 'Jaguar Warrior',
                      'added_in': 'Age of Empires II: The Conquerors',
                      'type': 'Infantry',
                      'civilization': ['Aztecs'],
                      'age_available': 'Castle Age',
                      'trained_at': ['Castle'],
                      'cost': {'food': 60, 'wood': 0, 'gold': 30},
                      'errors': {}},
  'War Wagon': { 'name': 'War Wagon',
                 'added_in': 'Age of Empires II: The Conquerors',
                 'type': 'Mounted archer',
                 'civilization': ['Koreans'],
                 'age_available': 'Castle Age',
                 'trained_at': ['Castle'],
                 'cost': {'food': 0, 'wood': 100, 'gold': 60},
                 'errors': {}},
  'Plumed Archer': { 'name': 'Plumed Archer',
                     'added_in': 'Age of Empires II: The Conquerors',
                     'type': 'Foot archer',
                     'civilization': ['Mayans'],
                     'age_available': 'Castle Age',
                     'trained_at': ['Castle'],
                     'cost': {'food': 0, 'wood': 55, 'gold': 55},
                     'errors': {}},
  'Conquistador': { 'name': 'Conquistador',
                    'added_in': 'Age of Empires II: The Conquerors',
                    'type': 'Cavalry',
                    'civilization': ['Spanish'],
                    'age_available': 'Castle Age',
                    'trained_at': ['Castle'],
                    'cost': {'food': 60, 'wood': 0, 'gold': 70},
                    'errors': {}},
  'Kamayuk': { 'name': 'Kamayuk',
               'added_in': 'Age of Empires II HD: The Forgotten',
               'type': 'Infantry',
               'civilization': ['Incas'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle'],
               'cost': {'food': 60, 'wood': 0, 'gold': 30},
               'errors': {}},
  'Genoese Crossbowman': { 'name': 'Genoese Crossbowman',
                           'added_in': 'Age of Empires II HD: The Forgotten',
                           'type': 'Foot archer',
                           'civilization': ['Italians'],
                           'age_available': 'Castle Age',
                           'trained_at': ['Castle'],
                           'cost': {'food': 0, 'wood': 45, 'gold': 40},
                           'errors': {}},
  'Magyar Huszar': { 'name': 'Magyar Huszar',
                     'added_in': 'Age of Empires II HD: The Forgotten',
                     'type': 'Cavalry',
                     'civilization': ['Magyars'],
                     'age_available': 'Castle Age',
                     'trained_at': ['Castle'],
                     'cost': {'food': 80, 'wood': 0, 'gold': 10},
                     'errors': {}},
  'Boyar': { 'name': 'Boyar',
             'added_in': 'Age of Empires II HD: The Forgotten',
             'type': 'Cavalry',
             'civilization': ['Slavs'],
             'age_available': 'Castle Age',
             'trained_at': ['Castle'],
             'cost': {'food': 50, 'wood': 0, 'gold': 80},
             'errors': {}},
  'Camel Archer': { 'name': 'Camel Archer',
                    'added_in': 'Age of Empires II HD: The African Kingdoms',
                    'type': 'Mounted archer',
                    'civilization': ['Berbers'],
                    'age_available': 'Castle Age',
                    'trained_at': ['Castle'],
                    'cost': {'food': 0, 'wood': 50, 'gold': 60},
                    'errors': {}},
  'Shotel Warrior': { 'name': 'Shotel Warrior',
                      'added_in': 'Age of Empires II HD: The African Kingdoms',
                      'type': 'Infantry',
                      'civilization': ['Ethiopians'],
                      'age_available': 'Castle Age',
                      'trained_at': ['Castle'],
                      'cost': {'food': 50, 'wood': 0, 'gold': 30},
                      'errors': {}},
  'Gbeto': { 'name': 'Gbeto',
             'added_in': 'Age of Empires II HD: The African Kingdoms',
             'type': 'Infantry',
             'civilization': ['Malians'],
             'age_available': 'Castle Age',
             'trained_at': ['Castle'],
             'cost': {'food': 50, 'wood': 0, 'gold': 40},
             'errors': {}},
  'Organ Gun': { 'name': 'Organ Gun',
                 'added_in': 'Age of Empires II HD: The African Kingdoms',
                 'type': 'Siege weapon',
                 'civilization': ['Portuguese'],
                 'age_available': 'Castle Age',
                 'trained_at': ['Castle'],
                 'cost': {'food': 0, 'wood': 80, 'gold': 56},
                 'errors': {}},
  'Arambai': { 'name': 'Arambai',
               'added_in': 'Age of Empires II HD: Rise of the Rajas',
               'type': 'Ranged cavalry',
               'civilization': ['Burmese'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle'],
               'cost': {'food': 0, 'wood': 75, 'gold': 60},
               'errors': {}},
  'Ballista Elephant': { 'name': 'Ballista Elephant',
                         'added_in': 'Age of Empires II HD: Rise of the Rajas',
                         'type': 'Cavalry',
                         'civilization': ['Khmer'],
                         'age_available': 'Castle Age',
                         'trained_at': ['Castle'],
                         'cost': {'food': 100, 'wood': 0, 'gold': 80},
                         'errors': {}},
  'Karambit Warrior': { 'name': 'Karambit Warrior',
                        'added_in': 'Age of Empires II HD: Rise of the Rajas',
                        'type': 'Infantry',
                        'civilization': ['Malay'],
                        'age_available': 'Castle Age',
                        'trained_at': ['Castle'],
                        'cost': {'food': 25, 'wood': 0, 'gold': 15},
                        'errors': {}},
  'Rattan Archer': { 'name': 'Rattan Archer',
                     'added_in': 'Age of Empires II HD: Rise of the Rajas',
                     'type': 'Foot archer',
                     'civilization': ['Vietnamese'],
                     'age_available': 'Castle Age',
                     'trained_at': ['Castle'],
                     'cost': {'food': 0, 'wood': 50, 'gold': 45},
                     'errors': {}},
  'Konnik': { 'name': 'Konnik',
              'added_in': 'Age of Empires II: Definitive Edition - The Last '
                          'Khans',
              'type': 'Cavalry',
              'civilization': ['Bulgarians'],
              'age_available': 'Castle Age',
              'trained_at': ['Castle', ''],
              'cost': {'food': 60, 'wood': 0, 'gold': 70},
              'errors': {}},
  'Kipchak': { 'name': 'Kipchak',
               'added_in': 'Age of Empires II: Definitive Edition - The Last '
                           'Khans',
               'type': 'Mounted archer',
               'civilization': ['Cumans'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle'],
               'cost': {'food': 0, 'wood': 60, 'gold': 35},
               'errors': {}},
  'Leitis': { 'name': 'Leitis',
              'added_in': 'Age of Empires II: Definitive Edition - The Last '
                          'Khans',
              'type': 'Cavalry',
              'civilization': ['Lithuanians'],
              'age_available': 'Castle Age',
              'trained_at': ['Castle'],
              'cost': {'food': 70, 'wood': 0, 'gold': 50},
              'errors': {}},
  'Keshik': { 'name': 'Keshik',
              'added_in': 'Age of Empires II: Definitive Edition - The Last '
                          'Khans',
              'type': 'Cavalry',
              'civilization': ['Tatars'],
              'age_available': 'Castle Age',
              'trained_at': ['Castle'],
              'cost': {'food': 60, 'wood': 0, 'gold': 40},
              'errors': {}},
  'Coustillier': { 'name': 'Coustillier',
                   'added_in': 'Age of Empires II: Definitive Edition - Lords '
                               'of the West',
                   'type': 'Cavalry',
                   'civilization': ['Burgundians'],
                   'age_available': 'Castle Age',
                   'trained_at': ['Castle'],
                   'cost': {'food': 55, 'wood': 0, 'gold': 55},
                   'errors': {}},
  'Serjeant': { 'name': 'Serjeant',
                'added_in': 'Age of Empires II: Definitive Edition - Lords of '
                            'the West',
                'type': 'Infantry',
                'civilization': ['Sicilians'],
                'age_available': 'Feudal Age',
                'trained_at': ['Castle', ''],
                'cost': {'food': 60, 'wood': 0, 'gold': 35},
                'errors': {}},
  'Hussite Wagon': { 'name': 'Hussite Wagon',
                     'added_in': 'Age of Empires II: Definitive Edition - Dawn '
                                 'of the Dukes',
                     'type': 'Siege unit',
                     'civilization': ['Bohemians'],
                     'age_available': 'Castle Age',
                     'trained_at': ['Castle'],
                     'cost': {'food': 0, 'wood': 110, 'gold': 70},
                     'errors': {}},
  'Obuch': { 'name': 'Obuch',
             'added_in': 'Age of Empires II: Definitive Edition - Dawn of the '
                         'Dukes',
             'type': 'Infantry',
             'civilization': ['Poles'],
             'age_available': 'Castle Age',
             'trained_at': ['Castle'],
             'cost': {'food': 55, 'wood': 0, 'gold': 20},
             'errors': {}},
  'Urumi Swordsman': { 'name': 'Urumi Swordsman',
                       'added_in': 'Age of Empires II: Definitive Edition - '
                                   'Dynasties of India',
                       'type': 'Infantry',
                       'civilization': ['Dravidians'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Castle'],
                       'cost': {'food': 65, 'wood': 0, 'gold': 20},
                       'errors': {}},
  'Chakram Thrower': { 'name': 'Chakram Thrower',
                       'added_in': 'Age of Empires II: Definitive Edition - '
                                   'Dynasties of India',
                       'type': 'Infantry',
                       'civilization': ['Gurjaras'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Castle'],
                       'cost': {'food': 65, 'wood': 0, 'gold': 30},
                       'errors': {}},
  'Ghulam': { 'name': 'Ghulam',
              'added_in': 'Age of Empires II: Definitive Edition - Dynasties '
                          'of India',
              'type': 'Infantry',
              'civilization': ['Hindustanis'],
              'age_available': 'Castle Age',
              'trained_at': ['Castle'],
              'cost': {'food': 30, 'wood': 0, 'gold': 45},
              'errors': {}},
  'Ratha': { 'name': 'Ratha',
             'added_in': 'Age of Empires II: Definitive Edition - Dynasties of '
                         'India',
             'type': 'Mounted archer',
             'civilization': ['Bengalis'],
             'age_available': 'Castle Age',
             'trained_at': ['Castle'],
             'cost': {'food': 0, 'wood': 60, 'gold': 60},
             'errors': {}}}