{ 'Militia': { 'name': 'Militia',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': 'Infantry',
               'civilization': 'Generic',
               'age_available': 'Dark Age',
               'trained_at': ['Barracks'],
               'cost': {'food': '60', 'wood': 0, 'gold': 0},
               'errors': {}},
  'Spearman': { 'name': 'Spearman',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Infantry',
                'civilization': 'Generic',
                'age_available': 'Feudal Age',
                'trained_at': ['Barracks'],
                'cost': {'food': '35', 'wood': '25', 'gold': 0},
                'errors': {}},
  'Eagle Scout': { 'name': 'Eagle Scout',
                   'added_in': 'Age of Empires II HD: The Forgotten',
                   'type': 'Infantry',
                   'civilization': ['Aztecs', 'Incas', 'Mayans'],
                   'age_available': 'Feudal Age',
                   'trained_at': ['Barracks'],
                   'cost': {'food': '20', 'wood': 0, 'gold': 0},
                   'errors': {}},
  'Condottiero': { 'name': 'Condottiero',
                   'added_in': 'Age of Empires II HD: The Forgotten',
                   'type': 'Infantry',
                   'civilization': ['Italians'],
                   'age_available': 'Imperial Age',
                   'trained_at': ['Barracks'],
                   'cost': {'food': '50', 'wood': 0, 'gold': 0},
                   'errors': {}},
  'Huskarl': { 'name': 'Huskarl',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': 'Infantry',
               'civilization': ['Goths'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle', 'Barracks'],
               'cost': {'food': '56', 'wood': 0, 'gold': 0},
               'errors': {}},
  'Archer': { 'name': 'Archer',
              'added_in': 'Age of Empires II: The Age of Kings',
              'type': 'Foot archer',
              'civilization': 'Generic',
              'age_available': 'Feudal Age',
              'trained_at': ['Archery Range'],
              'cost': {'food': 0, 'wood': '25', 'gold': '25'},
              'errors': {}},
  'Skirmisher': { 'name': 'Skirmisher',
                  'added_in': '',
                  'type': 'Foot archer',
                  'civilization': 'Generic',
                  'age_available': 'Feudal Age',
                  'trained_at': ['Archery Range'],
                  'cost': {'food': '25', 'wood': '35', 'gold': 0},
                  'errors': {}},
  'Cavalry Archer': { 'name': 'Cavalry Archer',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Mounted Archer',
                      'civilization': 'Generic',
                      'age_available': 'Castle Age',
                      'trained_at': ['Archery Range'],
                      'cost': {'food': 0, 'wood': '40', 'gold': 0},
                      'errors': {}},
  'Hand Cannoneer': { 'name': 'Hand Cannoneer',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Gunpowder unit',
                      'civilization': 'Generic',
                      'age_available': 'Imperial Age',
                      'trained_at': ['Archery Range'],
                      'cost': {'food': '45', 'wood': 0, 'gold': 0},
                      'errors': {}},
  'Elephant Archer': { 'name': 'Elephant Archer',
                       'added_in': 'Age of Empires II HD: The Forgotten',
                       'type': 'Mounted archer',
                       'civilization': ['Bengalis', 'Dravidians', 'Gurjaras'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Archery Range'],
                       'cost': {'food': '80', 'wood': 0, 'gold': 0},
                       'errors': {}},
  'Genitour': { 'name': 'Genitour',
                'added_in': 'Age of Empires II HD: The African Kingdoms',
                'type': 'Mounted Archer',
                'civilization': ['Berbers'],
                'age_available': 'Castle Age',
                'trained_at': ['Archery Range'],
                'cost': {'food': '40', 'wood': '35', 'gold': 0},
                'errors': {}},
  'Slinger': { 'name': 'Slinger',
               'added_in': 'Age of Empires II HD: The Forgotten',
               'type': 'Foot archer',
               'civilization': ['Incas'],
               'age_available': 'Castle Age',
               'trained_at': ['Archery Range'],
               'cost': {'food': '30', 'wood': 0, 'gold': 0},
               'errors': {}},
  'Scout Cavalry': { 'name': 'Scout Cavalry',
                     'added_in': 'Age of Empires II: The Age of Kings',
                     'type': 'Cavalry',
                     'civilization': 'Generic',
                     'age_available': 'Feudal Age',
                     'trained_at': ['Stable'],
                     'cost': {'food': '80', 'wood': 0, 'gold': 0},
                     'errors': {}},
  'Knight': { 'name': 'Knight',
              'added_in': 'Age of Empires II: The Age of Kings',
              'type': 'Cavalry',
              'civilization': 'Generic',
              'age_available': 'Castle Age',
              'trained_at': ['Stable'],
              'cost': {'food': '60', 'wood': 0, 'gold': 0},
              'errors': {}},
  'Camel Scout': { 'name': 'Camel Scout',
                   'added_in': 'Age of Empires II: Definitive Edition - '
                               'Dynasties of India',
                   'type': 'Cavalry',
                   'civilization': ['Gurjaras'],
                   'age_available': 'Feudal Age',
                   'trained_at': ['Stable'],
                   'cost': {'food': '55', 'wood': 0, 'gold': 0},
                   'errors': {}},
  'Battle Elephant': { 'name': 'Battle Elephant',
                       'added_in': 'Age of Empires II HD: Rise of the Rajas',
                       'type': 'Cavalry',
                       'civilization': [ 'Bengalis',
                                         'Burmese',
                                         'Dravidians',
                                         'Khmer',
                                         'Malay',
                                         'Vietnamese'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Stable'],
                       'cost': {'food': '110', 'wood': 0, 'gold': 0},
                       'errors': {}},
  'Steppe Lancer': { 'name': 'Steppe Lancer',
                     'added_in': 'Age of Empires II: Definitive Edition - The '
                                 'Last Khans',
                     'type': 'Cavalry',
                     'civilization': ['Cumans', 'Mongols', 'Tatars'],
                     'age_available': 'Castle Age',
                     'trained_at': ['Stable'],
                     'cost': {'food': '70', 'wood': 0, 'gold': 0},
                     'errors': {}},
  'Xolotl Warrior': { 'name': 'Xolotl Warrior',
                      'added_in': 'Age of Empires II: Definitive Edition - The '
                                  'Last Khans',
                      'type': 'Cavalry',
                      'civilization': ['Aztecs', 'Mayans', 'Incas'],
                      'age_available': 'Castle Age',
                      'trained_at': ['Stable'],
                      'cost': {'food': '60', 'wood': 0, 'gold': 0},
                      'errors': {}},
  'Shrivamsha Rider': { 'name': 'Shrivamsha Rider',
                        'added_in': 'Age of Empires II: Definitive Edition - '
                                    'Dynasties of India',
                        'type': 'Cavalry',
                        'civilization': ['Gurjaras'],
                        'age_available': 'Castle Age',
                        'trained_at': ['Stable'],
                        'cost': {'food': '70', 'wood': 0, 'gold': 0},
                        'errors': {}},
  'Tarkan': { 'name': 'Tarkan',
              'added_in': 'Age of Empires II: The Conquerors',
              'type': 'Cavalry',
              'civilization': ['Huns'],
              'age_available': 'Castle Age',
              'trained_at': ['Castle', ''],
              'cost': {'food': '60', 'wood': 0, 'gold': 0},
              'errors': {}},
  'Fishing Ship': { 'name': 'Fishing Ship',
                    'added_in': 'Age of Empires II: The Age of Kings',
                    'type': 'Civilian Ship',
                    'civilization': 'Generic',
                    'age_available': 'Dark Age',
                    'trained_at': ['Dock'],
                    'cost': {'food': 0, 'wood': '75', 'gold': 0},
                    'errors': {}},
  'Transport Ship': { 'name': 'Transport Ship',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Ship',
                      'civilization': 'Generic',
                      'age_available': 'Dark Age',
                      'trained_at': ['Dock', 'Harbor'],
                      'cost': {'food': 0, 'wood': '125', 'gold': 0},
                      'errors': {}},
  'Trade Cog': { 'name': 'Trade Cog',
                 'added_in': 'Age of Empires II: The Age of Kings',
                 'type': 'Civilian',
                 'civilization': 'Generic',
                 'age_available': 'Feudal Age',
                 'trained_at': ['Dock'],
                 'cost': {'food': 0, 'wood': '100', 'gold': '100'},
                 'errors': {}},
  'Galley': { 'name': 'Galley',
              'added_in': 'Age of Empires II: The Age of Kings',
              'type': 'Ship',
              'civilization': 'Generic',
              'age_available': 'Feudal Age',
              'trained_at': ['Dock'],
              'cost': {'food': 0, 'wood': '90', 'gold': '90'},
              'errors': {}},
  'Fire Galley': { 'name': 'Fire Galley',
                   'added_in': 'Age of Empires II HD: The African Kingdoms',
                   'type': 'Ship',
                   'civilization': 'Generic',
                   'age_available': 'Feudal Age',
                   'trained_at': ['Dock'],
                   'cost': {'food': 0, 'wood': '75', 'gold': '75'},
                   'errors': {}},
  'Demolition Raft': { 'name': 'Demolition Raft',
                       'added_in': 'Age of Empires II HD: The African Kingdoms',
                       'type': 'Ship',
                       'civilization': 'Generic',
                       'age_available': 'Feudal Age',
                       'trained_at': ['Dock'],
                       'cost': {'food': 0, 'wood': '70', 'gold': '70'},
                       'errors': {}},
  'Cannon Galleon': { 'name': 'Cannon Galleon',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Ship',
                      'civilization': 'Generic',
                      'age_available': 'Imperial Age',
                      'trained_at': ['Dock'],
                      'cost': {'food': 0, 'wood': '200', 'gold': '200'},
                      'errors': {}},
  'Longboat': { 'name': 'Longboat',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Ship',
                'civilization': ['Vikings'],
                'age_available': 'Castle Age',
                'trained_at': ['Dock'],
                'cost': {'food': 0, 'wood': '100', 'gold': '100'},
                'errors': {}},
  'Turtle Ship': { 'name': 'Turtle Ship',
                   'added_in': 'Age of Empires II: The Conquerors',
                   'type': 'Ship',
                   'civilization': ['Koreans'],
                   'age_available': 'Castle Age',
                   'trained_at': ['Dock'],
                   'cost': {'food': 0, 'wood': '152', 'gold': '152'},
                   'errors': {}},
  'Caravel': { 'name': 'Caravel',
               'added_in': 'Age of Empires II HD: The African Kingdoms',
               'type': 'Ship',
               'civilization': ['Portuguese'],
               'age_available': 'Castle Age',
               'trained_at': ['Dock'],
               'cost': {'food': 0, 'wood': '90', 'gold': 0},
               'errors': {}},
  'Thirisadai': { 'name': 'Thirisadai',
                  'added_in': 'Age of Empires II: Definitive Edition - '
                              'Dynasties of India',
                  'type': 'Ship',
                  'civilization': ['Dravidians'],
                  'age_available': 'Imperial Age',
                  'trained_at': ['Dock'],
                  'cost': {'food': 0, 'wood': '180', 'gold': '180'},
                  'errors': {}},
  'Battering Ram': { 'name': 'Battering Ram',
                     'added_in': 'Age of Empires II: The Age of Kings',
                     'type': 'Siege unit',
                     'civilization': 'Generic',
                     'age_available': 'Castle Age',
                     'trained_at': ['Siege Workshop'],
                     'cost': {'food': 0, 'wood': '160', 'gold': '160'},
                     'errors': {}},
  'Mangonel': { 'name': 'Mangonel',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Siege unit',
                'civilization': 'Generic',
                'age_available': 'Castle Age',
                'trained_at': ['Siege Workshop'],
                'cost': {'food': 0, 'wood': '160', 'gold': '160'},
                'errors': {}},
  'Scorpion': { 'name': 'Scorpion',
                'added_in': '',
                'type': 'Siege unit',
                'civilization': 'Generic',
                'age_available': 'Castle Age',
                'trained_at': ['Siege Workshop'],
                'cost': {'food': 0, 'wood': '75', 'gold': '75'},
                'errors': {}},
  'Bombard Cannon': { 'name': 'Bombard Cannon',
                      'added_in': 'Age of Empires II: The Age of Kings',
                      'type': 'Siege unit',
                      'civilization': 'Generic',
                      'age_available': 'Imperial Age',
                      'trained_at': ['Siege Workshop'],
                      'cost': {'food': 0, 'wood': '225', 'gold': '225'},
                      'errors': {}},
  'Siege Tower': { 'name': 'Siege Tower',
                   'added_in': 'Age of Empires II HD: The African Kingdoms',
                   'type': 'Siege unit',
                   'civilization': 'Generic',
                   'age_available': 'Castle Age',
                   'trained_at': ['Siege Workshop'],
                   'cost': {'food': 0, 'wood': '200', 'gold': '200'},
                   'errors': {}},
  'Armored Elephant': { 'name': 'Armored Elephant',
                        'added_in': 'Age of Empires II: Definitive Edition - '
                                    'Dynasties of India',
                        'type': 'Cavalry',
                        'civilization': [ 'Bengalis',
                                          'Dravidians',
                                          'Gurjaras',
                                          'Hindustanis'],
                        'age_available': 'Castle Age',
                        'trained_at': ['Siege Workshop'],
                        'cost': {'food': '130', 'wood': 0, 'gold': 0},
                        'errors': {}},
  'Villager': { 'name': 'Villager',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': None,
                'civilization': 'Generic',
                'age_available': 'Dark Age',
                'trained_at': ['Town Center'],
                'cost': {'food': '50', 'wood': 0, 'gold': 0},
                'errors': { 'TypeError': "'NoneType' object has no attribute "
                                         "'text'"}},
  'Burgundians': { 'name': 'Burgundians',
                   'added_in': 'Age of Empires II: Definitive Edition - Lords '
                               'of the West',
                   'type': None,
                   'civilization': None,
                   'age_available': None,
                   'trained_at': None,
                   'cost': {'food': 0, 'wood': 0, 'gold': 0},
                   'errors': { 'TypeError': "'NoneType' object has no "
                                            "attribute 'find'",
                               'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                               'AgeError': "'NoneType' object has no attribute "
                                           "'find'",
                               'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Monk': { 'name': 'Monk',
            'added_in': 'Age of Empires II: The Age of Kings',
            'type': None,
            'civilization': 'Generic',
            'age_available': 'Castle Age',
            'trained_at': ['Monastery'],
            'cost': {'food': 0, 'wood': 0, 'gold': 0},
            'errors': { 'TypeError': "'NoneType' object has no attribute "
                                     "'text'"}},
  'Missionary': { 'name': 'Missionary',
                  'added_in': 'Age of Empires II: The Conquerors',
                  'type': 'Cavalry',
                  'civilization': ['Spanish'],
                  'age_available': 'Castle Age',
                  'trained_at': ['Monastery'],
                  'cost': {'food': 0, 'wood': 0, 'gold': 0},
                  'errors': {}},
  'Trade Cart': { 'name': 'Trade Cart',
                  'added_in': 'Age of Empires II: The Age of Kings',
                  'type': None,
                  'civilization': 'Generic',
                  'age_available': 'Feudal Age',
                  'trained_at': ['Market'],
                  'cost': {'food': 0, 'wood': '100', 'gold': '100'},
                  'errors': { 'TypeError': "'NoneType' object has no attribute "
                                           "'text'"}},
  None: { 'name': None,
          'added_in': None,
          'type': None,
          'civilization': None,
          'age_available': None,
          'trained_at': None,
          'cost': {'food': 0, 'wood': 0, 'gold': 0},
          'errors': { 'NameError': "'NoneType' object has no attribute 'text'",
                      'AddedInError': "'NoneType' object has no attribute "
                                      "'find'",
                      'TypeError': "'NoneType' object has no attribute 'find'",
                      'CivError': AttributeError("'NoneType' object has no attribute 'find'"),
                      'AgeError': "'NoneType' object has no attribute 'find'",
                      'TrainBuildingError': AttributeError("'NoneType' object has no attribute 'find'")}},
  'Petard': { 'name': 'Petard',
              'added_in': 'Age of Empires II: The Conquerors',
              'type': 'Siege unit',
              'civilization': 'Generic',
              'age_available': 'Castle Age',
              'trained_at': ['Castle'],
              'cost': {'food': '65', 'wood': 0, 'gold': 0},
              'errors': {}},
  'Trebuchet': { 'name': 'Trebuchet',
                 'added_in': 'Age of Empires II: The Age of Kings',
                 'type': 'Siege unit',
                 'civilization': 'Generic',
                 'age_available': 'Imperial Age',
                 'trained_at': ['Castle'],
                 'cost': {'food': 0, 'wood': '200', 'gold': '200'},
                 'errors': {}},
  'Longbowman': { 'name': 'Longbowman',
                  'added_in': 'Age of Empires II: The Age of Kings',
                  'type': 'Foot Archer',
                  'civilization': ['Britons'],
                  'age_available': 'Castle Age',
                  'trained_at': ['Castle'],
                  'cost': {'food': 0, 'wood': '35', 'gold': '35'},
                  'errors': {}},
  'Cataphract': { 'name': 'Cataphract',
                  'added_in': 'Age of Empires II: The Age of Kings',
                  'type': 'Cavalry',
                  'civilization': ['Byzantines'],
                  'age_available': 'Castle Age',
                  'trained_at': ['Castle'],
                  'cost': {'food': '70', 'wood': 0, 'gold': 0},
                  'errors': {}},
  'Woad Raider': { 'name': 'Woad Raider',
                   'added_in': 'Age of Empires II: The Age of Kings',
                   'type': 'Infantry',
                   'civilization': ['Celts'],
                   'age_available': 'Castle Age',
                   'trained_at': ['Castle'],
                   'cost': {'food': '65', 'wood': 0, 'gold': 0},
                   'errors': {}},
  'Chu Ko Nu': { 'name': 'Chu Ko Nu',
                 'added_in': 'Age of Empires II: The Age of Kings',
                 'type': 'Foot archer',
                 'civilization': ['Chinese'],
                 'age_available': 'Castle Age',
                 'trained_at': ['Castle'],
                 'cost': {'food': 0, 'wood': '40', 'gold': '40'},
                 'errors': {}},
  'Throwing Axeman': { 'name': 'Throwing Axeman',
                       'added_in': 'Age of Empires II: The Age of Kings',
                       'type': 'Infantry',
                       'civilization': ['Franks'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Castle'],
                       'cost': {'food': '55', 'wood': 0, 'gold': 0},
                       'errors': {}},
  'Samurai': { 'name': 'Samurai',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': 'Infantry',
               'civilization': ['Japanese'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle'],
               'cost': {'food': '60', 'wood': 0, 'gold': 0},
               'errors': {}},
  'Mangudai': { 'name': 'Mangudai',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Mounted archer',
                'civilization': ['Mongols'],
                'age_available': 'Castle Age',
                'trained_at': ['Castle'],
                'cost': {'food': 0, 'wood': '55', 'gold': '55'},
                'errors': {}},
  'War Elephant': { 'name': 'War Elephant',
                    'added_in': 'Age of Empires II: The Age of Kings',
                    'type': 'Cavalry',
                    'civilization': ['Persians'],
                    'age_available': 'Castle Age',
                    'trained_at': ['Castle'],
                    'cost': {'food': '170', 'wood': 0, 'gold': 0},
                    'errors': {}},
  'Mameluke': { 'name': 'Mameluke',
                'added_in': 'Age of Empires II: The Age of Kings',
                'type': 'Cavalry',
                'civilization': ['Saracens'],
                'age_available': 'Castle Age',
                'trained_at': ['Castle'],
                'cost': {'food': '55', 'wood': 0, 'gold': 0},
                'errors': {}},
  'Teutonic Knight': { 'name': 'Teutonic Knight',
                       'added_in': 'Age of Empires II: The Age of Kings',
                       'type': 'Infantry',
                       'civilization': ['Teutons'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Castle'],
                       'cost': {'food': '85', 'wood': 0, 'gold': 0},
                       'errors': {}},
  'Janissary': { 'name': 'Janissary',
                 'added_in': 'Age of Empires II: The Age of Kings',
                 'type': 'Gunpowder unit',
                 'civilization': ['Turks'],
                 'age_available': 'Castle Age',
                 'trained_at': ['Castle'],
                 'cost': {'food': '60', 'wood': 0, 'gold': 0},
                 'errors': {}},
  'Berserk': { 'name': 'Berserk',
               'added_in': 'Age of Empires II: The Age of Kings',
               'type': 'Infantry',
               'civilization': ['Vikings'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle'],
               'cost': {'food': '65', 'wood': 0, 'gold': 0},
               'errors': {}},
  'Jaguar Warrior': { 'name': 'Jaguar Warrior',
                      'added_in': 'Age of Empires II: The Conquerors',
                      'type': 'Infantry',
                      'civilization': ['Aztecs'],
                      'age_available': 'Castle Age',
                      'trained_at': ['Castle'],
                      'cost': {'food': '60', 'wood': 0, 'gold': 0},
                      'errors': {}},
  'War Wagon': { 'name': 'War Wagon',
                 'added_in': 'Age of Empires II: The Conquerors',
                 'type': 'Mounted archer',
                 'civilization': ['Koreans'],
                 'age_available': 'Castle Age',
                 'trained_at': ['Castle'],
                 'cost': {'food': 0, 'wood': '100', 'gold': '100'},
                 'errors': {}},
  'Plumed Archer': { 'name': 'Plumed Archer',
                     'added_in': 'Age of Empires II: The Conquerors',
                     'type': 'Foot archer',
                     'civilization': ['Mayans'],
                     'age_available': 'Castle Age',
                     'trained_at': ['Castle'],
                     'cost': {'food': 0, 'wood': '', 'gold': ''},
                     'errors': {}},
  'Conquistador': { 'name': 'Conquistador',
                    'added_in': 'Age of Empires II: The Conquerors',
                    'type': 'Cavalry',
                    'civilization': ['Spanish'],
                    'age_available': 'Castle Age',
                    'trained_at': ['Castle'],
                    'cost': {'food': '60', 'wood': 0, 'gold': 0},
                    'errors': {}},
  'Kamayuk': { 'name': 'Kamayuk',
               'added_in': 'Age of Empires II HD: The Forgotten',
               'type': 'Infantry',
               'civilization': ['Incas'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle'],
               'cost': {'food': '60', 'wood': 0, 'gold': 0},
               'errors': {}},
  'Genoese Crossbowman': { 'name': 'Genoese Crossbowman',
                           'added_in': 'Age of Empires II HD: The Forgotten',
                           'type': 'Foot archer',
                           'civilization': ['Italians'],
                           'age_available': 'Castle Age',
                           'trained_at': ['Castle'],
                           'cost': {'food': 0, 'wood': '45', 'gold': '45'},
                           'errors': {}},
  'Magyar Huszar': { 'name': 'Magyar Huszar',
                     'added_in': 'Age of Empires II HD: The Forgotten',
                     'type': 'Cavalry',
                     'civilization': ['Magyars'],
                     'age_available': 'Castle Age',
                     'trained_at': ['Castle'],
                     'cost': {'food': '80', 'wood': 0, 'gold': 0},
                     'errors': {}},
  'Boyar': { 'name': 'Boyar',
             'added_in': 'Age of Empires II HD: The Forgotten',
             'type': 'Cavalry',
             'civilization': ['Slavs'],
             'age_available': 'Castle Age',
             'trained_at': ['Castle'],
             'cost': {'food': '50', 'wood': 0, 'gold': 0},
             'errors': {}},
  'Camel Archer': { 'name': 'Camel Archer',
                    'added_in': 'Age of Empires II HD: The African Kingdoms',
                    'type': 'Mounted archer',
                    'civilization': ['Berbers'],
                    'age_available': 'Castle Age',
                    'trained_at': ['Castle'],
                    'cost': {'food': 0, 'wood': '50', 'gold': '50'},
                    'errors': {}},
  'Shotel Warrior': { 'name': 'Shotel Warrior',
                      'added_in': 'Age of Empires II HD: The African Kingdoms',
                      'type': 'Infantry',
                      'civilization': ['Ethiopians'],
                      'age_available': 'Castle Age',
                      'trained_at': ['Castle'],
                      'cost': {'food': '50', 'wood': 0, 'gold': 0},
                      'errors': {}},
  'Gbeto': { 'name': 'Gbeto',
             'added_in': 'Age of Empires II HD: The African Kingdoms',
             'type': 'Infantry',
             'civilization': ['Malians'],
             'age_available': 'Castle Age',
             'trained_at': ['Castle'],
             'cost': {'food': '50', 'wood': 0, 'gold': 0},
             'errors': {}},
  'Organ Gun': { 'name': 'Organ Gun',
                 'added_in': 'Age of Empires II HD: The African Kingdoms',
                 'type': 'Siege weapon',
                 'civilization': ['Portuguese'],
                 'age_available': 'Castle Age',
                 'trained_at': ['Castle'],
                 'cost': {'food': 0, 'wood': '80', 'gold': 0},
                 'errors': {}},
  'Arambai': { 'name': 'Arambai',
               'added_in': 'Age of Empires II HD: Rise of the Rajas',
               'type': 'Ranged cavalry',
               'civilization': ['Burmese'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle'],
               'cost': {'food': 0, 'wood': '75', 'gold': '75'},
               'errors': {}},
  'Ballista Elephant': { 'name': 'Ballista Elephant',
                         'added_in': 'Age of Empires II HD: Rise of the Rajas',
                         'type': 'Cavalry',
                         'civilization': ['Khmer'],
                         'age_available': 'Castle Age',
                         'trained_at': ['Castle'],
                         'cost': {'food': '100', 'wood': 0, 'gold': 0},
                         'errors': {}},
  'Karambit Warrior': { 'name': 'Karambit Warrior',
                        'added_in': 'Age of Empires II HD: Rise of the Rajas',
                        'type': 'Infantry',
                        'civilization': ['Malay'],
                        'age_available': 'Castle Age',
                        'trained_at': ['Castle'],
                        'cost': {'food': '25', 'wood': 0, 'gold': 0},
                        'errors': {}},
  'Rattan Archer': { 'name': 'Rattan Archer',
                     'added_in': 'Age of Empires II HD: Rise of the Rajas',
                     'type': 'Foot archer',
                     'civilization': ['Vietnamese'],
                     'age_available': 'Castle Age',
                     'trained_at': ['Castle'],
                     'cost': {'food': 0, 'wood': '50', 'gold': '50'},
                     'errors': {}},
  'Konnik': { 'name': 'Konnik',
              'added_in': 'Age of Empires II: Definitive Edition - The Last '
                          'Khans',
              'type': 'Cavalry',
              'civilization': ['Bulgarians'],
              'age_available': 'Castle Age',
              'trained_at': ['Castle', ''],
              'cost': {'food': '60', 'wood': 0, 'gold': 0},
              'errors': {}},
  'Kipchak': { 'name': 'Kipchak',
               'added_in': 'Age of Empires II: Definitive Edition - The Last '
                           'Khans',
               'type': 'Mounted archer',
               'civilization': ['Cumans'],
               'age_available': 'Castle Age',
               'trained_at': ['Castle'],
               'cost': {'food': 0, 'wood': '60', 'gold': '60'},
               'errors': {}},
  'Leitis': { 'name': 'Leitis',
              'added_in': 'Age of Empires II: Definitive Edition - The Last '
                          'Khans',
              'type': 'Cavalry',
              'civilization': ['Lithuanians'],
              'age_available': 'Castle Age',
              'trained_at': ['Castle'],
              'cost': {'food': '70', 'wood': 0, 'gold': 0},
              'errors': {}},
  'Keshik': { 'name': 'Keshik',
              'added_in': 'Age of Empires II: Definitive Edition - The Last '
                          'Khans',
              'type': 'Cavalry',
              'civilization': ['Tatars'],
              'age_available': 'Castle Age',
              'trained_at': ['Castle'],
              'cost': {'food': '60', 'wood': 0, 'gold': 0},
              'errors': {}},
  'Coustillier': { 'name': 'Coustillier',
                   'added_in': 'Age of Empires II: Definitive Edition - Lords '
                               'of the West',
                   'type': 'Cavalry',
                   'civilization': ['Burgundians'],
                   'age_available': 'Castle Age',
                   'trained_at': ['Castle'],
                   'cost': {'food': '55', 'wood': 0, 'gold': 0},
                   'errors': {}},
  'Serjeant': { 'name': 'Serjeant',
                'added_in': 'Age of Empires II: Definitive Edition - Lords of '
                            'the West',
                'type': 'Infantry',
                'civilization': ['Sicilians'],
                'age_available': 'Feudal Age',
                'trained_at': ['Castle', ''],
                'cost': {'food': '60', 'wood': 0, 'gold': 0},
                'errors': {}},
  'Hussite Wagon': { 'name': 'Hussite Wagon',
                     'added_in': 'Age of Empires II: Definitive Edition - Dawn '
                                 'of the Dukes',
                     'type': 'Siege unit',
                     'civilization': ['Bohemians'],
                     'age_available': 'Castle Age',
                     'trained_at': ['Castle'],
                     'cost': {'food': 0, 'wood': '110', 'gold': '110'},
                     'errors': {}},
  'Obuch': { 'name': 'Obuch',
             'added_in': 'Age of Empires II: Definitive Edition - Dawn of the '
                         'Dukes',
             'type': 'Infantry',
             'civilization': ['Poles'],
             'age_available': 'Castle Age',
             'trained_at': ['Castle'],
             'cost': {'food': '55', 'wood': 0, 'gold': 0},
             'errors': {}},
  'Urumi Swordsman': { 'name': 'Urumi Swordsman',
                       'added_in': 'Age of Empires II: Definitive Edition - '
                                   'Dynasties of India',
                       'type': 'Infantry',
                       'civilization': ['Dravidians'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Castle'],
                       'cost': {'food': '65', 'wood': 0, 'gold': 0},
                       'errors': {}},
  'Chakram Thrower': { 'name': 'Chakram Thrower',
                       'added_in': 'Age of Empires II: Definitive Edition - '
                                   'Dynasties of India',
                       'type': 'Infantry',
                       'civilization': ['Gurjaras'],
                       'age_available': 'Castle Age',
                       'trained_at': ['Castle'],
                       'cost': {'food': '65', 'wood': 0, 'gold': 0},
                       'errors': {}},
  'Ghulam': { 'name': 'Ghulam',
              'added_in': 'Age of Empires II: Definitive Edition - Dynasties '
                          'of India',
              'type': 'Infantry',
              'civilization': ['Hindustanis'],
              'age_available': 'Castle Age',
              'trained_at': ['Castle'],
              'cost': {'food': '30', 'wood': 0, 'gold': 0},
              'errors': {}},
  'Ratha': { 'name': 'Ratha',
             'added_in': 'Age of Empires II: Definitive Edition - Dynasties of '
                         'India',
             'type': 'Mounted archer',
             'civilization': ['Bengalis'],
             'age_available': 'Castle Age',
             'trained_at': ['Castle'],
             'cost': {'food': 0, 'wood': '60', 'gold': '60'},
             'errors': {}}}